[project]
name = 'Blockchain-Based-Security-Surveillance-Network-Coordination'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.camera-network]
path = 'contracts/camera-network.clar'
clarity_version = 2
epoch = 2.5

[contracts.vidence-management]
path = 'contracts/vidence-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
